apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "app-demo-sampla-2"
  description: "app-demo-sampla-2"
  annotations:
    github.com/project-slug: veecode-homolog/app-demo-sampla-2
    backstage.io/techdocs-ref: dir:.
    github.com/workflows: publish.yml
    kong-manager/service-name: app.app-demo-sampla-2.app-demo-sampla-2-service-0.80
    kong-manager/instance: /kong-manager/cluster-veecode
spec:
  type: devops
  lifecycle: experimental
  owner: "group:default/admin"
  providesApis:
    - app-demo-sampla-2
