
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: app-demo-sampla-2-cors
plugin: cors
config:
  origins:
    - https://devportal-homolog.apr.vee.codes
    - https://devportal.apr.vee.codes
  credentials: false
  max_age: 3600
  preflight_continue: false
---
apiVersion: v1
kind: Service
metadata:
  name: app-demo-sampla-2-service-0
spec:
  externalName: viacep.com.br
  type: ExternalName
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-demo-sampla-2
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/strip-path: "true"
    konghq.com/plugins: app-demo-sampla-2-cors
spec:
  rules:
    - host: kong.vkpr.platform.vee.codes
      http:
        paths:
          - backend:
              service:
                name: app-demo-sampla-2-service-0
                port:
                  number: 80
            pathType: ImplementationSpecific
            path: /app-demo-sampla-2
  ingressClassName: kong
